### PR TITLE
Added RTU over TCP ModbusSlave support

### PR DESCRIPTION
**Pull request by eli-mcgowan**
Added RTU over TCP ModbusSlave support

### CODE REVIEW

**Comment by eli-mcgowan** [comment]
If I made an error submitting through git, please let me know how to fix it.
Only 4 files were changed.

**Comment by axuan25** [comment]
Why log4j and not Logback? All debug level?

**Comment by steveohara** [comment]
I'm afraid there's something horrible about this commit. Haven't had time to look into yet but it looks as though eli-mcgowan has branched from a release way way back in history :(

**Comment by eli-mcgowan** [comment]
I'll try fixing this commit, so I will close this request.

**Pull request closed without merging**
