### PR TITLE
 Fixed slave responding to wrong request

### LINKED ISSUE #62: Listen to one specific UnitID with serial RTU slave?
I'm trying to write an application that is supposed to emulate a slave on a specific address. So far I have gotten the program to receive data through the serial port and it sends back som messages to the master. But I sends a lot of exception messages because it receives messages ment for another unit. This is not good for the master program as it only expects one answer but gets a response from two units.

Is there a way to stop this behavior?
To create the slave I do: `ModbusSlave slave = ModbusSlaveFactory.createSerialSlave(params);`
I create a ProcessImageImplementation like this: ``
And add it to the slave like this: ``

Is there something that I am doing wrong, something about the library I am using in a wrong way?

Otherwise this is a very good feature to have as it allows for simulating one of many devices on  a network.

### PR DESCRIPTION
**Pull request by NogginBops**
This makes the slave implementation not answer modbus messages not intended for the slave. Fixes #62

### CODE REVIEW

**Comment by steveohara** [comment]
Thanks for the fix - sorry to be a pain, but I'm getting stricter with taking code commits without unit tests.
Can you check to see if there are any unit tests that cover this scenario and if not, add one?

**Comment by NogginBops** [comment]
I'll see if I can do something about the tests. :)

**Comment by NogginBops** [comment]
There looks like there is a test in TestModbusSerialRTUMasterRead.java - testBadUnitIdRequest()

```java
@Test
public void testBadUnitIdRequest() {
    try {
        master.readCoils(UNIT_ID + 10, 0, 1).getBit(0);
        fail("Failed check for invalid Unit ID");
    }
    catch (Exception e) {
        logger.info("Got expected error response (testBadUnitIdRequest) - {}", e.getMessage());
    }
}
```

But the question here is how the test passed before. I have no way to actually run the serial tests on actual hardware, do you have the ability to do this?

**Comment by steveohara** [comment]
I use com0com on a Windows machine to test the serial implementation

**Comment by steveohara** [comment]
Ok, I understand the problem now.
Hoever, your fix is not correct because it a response should be sent back for TCP/UDP slaves. The response should not be sent back for Serial slaves only.

I'm working on a fix now.

**Pull request closed without merging**
